book_api/book_api/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [   
   # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('user/', include('user.urls', namespace='user')),
    path('user/', include('django.contrib.auth.urls')),
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
]

book_api/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.search_by_id, name='home'),
    path('detail/<str:pk>/', views.details, name='detail'),
    path('csv/<str:pk>', views.csv_file, name='csv_file'),
    path('pdf/<str:pk>', views.pdf_file, name='pdf_file'),    
]

book_api/user/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'user'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

book_api/main/models.py
from django.db import models
from user.models import CustomUser
# Create your models here.
class Book(models.Model):
    id_book = models.PositiveIntegerField(primary_key=True)
    title = models.CharField(max_length=150, blank=False)
    publication_date = models.PositiveIntegerField(blank=False)

    def __str__(self) -> str:
        return str(self.id_book)

class Comment(models.Model):
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'ID: {self.book}, Created: {self.created_date}'

        

book_api/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    pass

    def __str__(self) -> str:
        return self.username
        

book_api/main/forms.py
from django import forms
from .models import Comment
 
class CommentForm(forms.ModelForm):
    text = forms.CharField(label ="", widget = forms.Textarea(
    attrs ={
        'class':'form-control',
        'placeholder':'Comment here !',
        'rows':4,
        'cols':50
    }))
    class Meta:
        model = Comment
        fields =['text']

book_api/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name',)


class CustomUserChangeForm(UserChangeForm):  
    class Meta:
        model = CustomUser
        fields = ('username',)

book_api/main/views.py
from django.shortcuts import render
from .forms import CommentForm
from django.shortcuts import get_object_or_404, redirect, render
import requests
from main.models import Book, Comment 
import json 
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
import csv
from django.http import HttpResponse
from reportlab.lib.units import inch
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter



# Create your views here.

@login_required(login_url='login')
def search_by_id(request):
    info = {}
    id_book =  None 
    title = None
    publication_date = None
    data = None
    if  'id' in request.GET:
        id = request.GET['id']  
        url = 'https://www.etnassoft.com/api/v1/get/?id=%s' % id
        response = requests.get(url)
        if response.json():

            info = response.json()[0]
            id_book = int(info['ID'])    
            title = info['title']
            publication_date = int(info['publisher_date'])
            print(response.json())

            for key, value in info.items():
                print(f'{key}: {value}')

            if Book.objects.filter(id_book=id_book).exists():
                pass  
                          
            else:
                book = Book.objects.create(id_book=id_book, title=title, publication_date=publication_date)
                book.save()
            
            data = Book.objects.get(id_book=id_book)

            return render(request, 'main/home.html', {'book': data, 'info': info})
        else:
            pass

        
    return render(request, 'main/home.html', {'book': data} )

@login_required(login_url='login')
def details(request, pk):
    book = Book.objects.get(id_book=pk)
    
    if request.method == 'POST':
        cf = CommentForm(request.POST or None)
        if cf.is_valid():
            text = request.POST.get('text')
            comment = Comment.objects.create(book = book , user = request.user, text = text)
            comment.save()
    else:
        cf = CommentForm()
       
    context ={
      'book': book,  
      'comment_form':cf,
      }   
       
    return render(request, 'main/detail.html', context)

@login_required(login_url='login')
def csv_file(request, *args, **kwargs):
    id = kwargs.get('pk')      
    url = 'https://www.etnassoft.com/api/v1/get/?id=%s' % id
    data = requests.get(url)
    info = data.json()[0].items()
    print(data.json())
    response = HttpResponse('text/csv')
    response['Content-Disposition'] = 'attachment; filename=book.csv'
    write = csv.writer(response)
    header = []
    row = []
    for key,value in info:
        header.append(key) 
        row.append(value) 

    write.writerow(header)
    write.writerow(row)

    return response

@login_required(login_url='login')
def pdf_file(request, pk):
    # Create Bytestream buffer
    buffer = io.BytesIO()
    # Create the PDF object, using the buffer as its "file."
    c = canvas.Canvas(buffer, pagesize=letter, bottomup=0)
    # Create a text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 14)

    book = Book.objects.get(id_book=pk)

    lines = [
		f'ID : {book.id_book} ',
		f'Title: {book.title}',
        f'Publication date: {book.publication_date}',
        ]

    for line in lines:
        textob.textLine(line)
        
    # Finish Up
    c.drawText(textob)
    c.showPage()
    c.save()
    buffer.seek(0)
    
    return FileResponse(buffer, as_attachment=True, filename='book.pdf')




    
    

book_api/user/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

# Create your views here.
# def signin(request):
#     return render(request,'user/signin.html')

# def signup(request):
#     return render(request, 'user/signup.html')

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

book_api/main/templates/main/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="text-center">
  <h1>Book info</h1>
  <h3>ID: {{book.id_book}}</h3>
  <h3>Title: {{book.title}}</h3>
  <h3>Publication date: {{book.publication_date}}</h3>
  
  <p></p>
  <p></p>   
  <form method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <input type="submit" name="comment" class="btn btn-warning">
    </form>
  
  <br>
  <br>
  <p>
    <a href="{% url 'main:home' %}" class="btn btn-outline-dark btn-sm m-1">Home</a>
    <a href="{% url 'main:csv_file' book.id_book %}" class="btn btn-outline-dark btn-sm m-1">CSV File</a>
    <a href="{% url 'main:pdf_file' book.id_book %}" class="btn btn-outline-dark btn-sm m-1">PDF File</a>
  </p>  
  </div>
{% endblock %}

book_api/main/templates/main/home.html
{% extends 'base.html '%}
{% block title %}
 Home
{% endblock title %}

{% block content %}

<nav class="row" style="background: grey; color: white;">
    <div align="center"><h1 class="col-md-3 text-center">Public Api for Books</h1></div>
    <div align="right">
      {% if user.is_authenticated %}
        <h3 class="col-md-3 ">Hi {{ user.username }}! </h3>
        <h3 class="col-md-3 "><a href="{% url 'logout' %}">Log Out</a></h3>
      {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a> |
        <a href="{% url 'user:signup' %}">Sign Up</a>
      {% endif %}
    </div>
</nav>
<br />

  <center class="row">
    <form action="" method="get" class="col-md-6 col-md-offset-3">
        <div class="input-group">
        <input type="text" class="form-control" name="id" placeholder="Search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
        <form>
  </center>
  {% if book %}
    <div class="col-md-6 col-md-offset-3">
        <h3>ID : {{book.id_book}}</h1>
        <h5>Title: {{book.title}}</h5>
        <h5>Publication date: {{book.publication_date}}</h5>
        <a href="{% url 'main:detail' book.id_book %}" class="btn btn-outline-dark btn-sm m-1">Details</a>
        <a href="{% url 'main:csv_file' book.id_book %}" class="btn btn-outline-dark btn-sm m-1">CSV File</a>
        <a href="{% url 'main:pdf_file' book.id_book %}" class="btn btn-outline-dark btn-sm m-1">PDF File</a>  
          

    </div>
  {% else %} 
  <div class="col-md-6 col-md-offset-3">
    <h3>Couldn't find a book the match that ID. Try again! </h3>
  </div>  
  {% endif %}
  
  {% endblock %}

book_api/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    {% block title %}

    {% endblock title %}
  </title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
 
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>